## Benchmark MMTF Hadoop Sequence File filtering

In [1]:
import pandas as pd
import papermill as pm
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import psutil
n_cores = psutil.cpu_count(logical=True)
n_cpus = psutil.cpu_count(logical=False)
print("cores:", n_cores)
print("cpus: ", n_cpus)

cores: 4
cpus:  2

In [3]:
dataset = "full"
coresets = [1,2,3] + list(range(4, n_cores+1, 4))
print(coresets)

[1, 2, 3, 4]

In [4]:
for cores in coresets:
    pm.execute_notebook(
        'tasks/Filter.ipynb',
        '../output/Filter_' + str(cores) + "_" + dataset + '.ipynb',
        parameters = dict(cores=cores, path='../data/' + dataset)
    )

Input Notebook:  tasks/Filter.ipynb
Output Notebook: ../output/Filter_1_full.ipynb
100%|██████████| 7/7 [01:23<00:00, 11.88s/it]
Input Notebook:  tasks/Filter.ipynb
Output Notebook: ../output/Filter_2_full.ipynb
100%|██████████| 7/7 [00:56<00:00,  8.05s/it]
Input Notebook:  tasks/Filter.ipynb
Output Notebook: ../output/Filter_3_full.ipynb
100%|██████████| 7/7 [00:57<00:00,  8.19s/it]
Input Notebook:  tasks/Filter.ipynb
Output Notebook: ../output/Filter_4_full.ipynb
100%|██████████| 7/7 [00:57<00:00,  8.28s/it]

In [5]:
nbs = pm.read_notebooks('../output/')
nbs.dataframe

,name,value,type,filename,key
0,cores,1,parameter,Filter_1_full.ipynb,Filter_1_full.ipynb
1,path,../data/full,parameter,Filter_1_full.ipynb,Filter_1_full.ipynb
2,filter,62.5429,record,Filter_1_full.ipynb,Filter_1_full.ipynb
3,filter_total,80.7885,record,Filter_1_full.ipynb,Filter_1_full.ipynb
4,cores,2,parameter,Filter_2_full.ipynb,Filter_2_full.ipynb
5,path,../data/full,parameter,Filter_2_full.ipynb,Filter_2_full.ipynb
6,filter,35.8053,record,Filter_2_full.ipynb,Filter_2_full.ipynb
7,filter_total,54.0278,record,Filter_2_full.ipynb,Filter_2_full.ipynb
8,cores,3,parameter,Filter_3_full.ipynb,Filter_3_full.ipynb
9,path,../data/full,parameter,Filter_3_full.ipynb,Filter_3_full.ipynb
10,filter,36.6299,record,Filter_3_full.ipynb,Filter_3_full.ipynb
11,filter_total,54.9289,record,Filter_3_full.ipynb,Filter_3_full.ipynb
12,cores,4,parameter,Filter_4_full.ipynb,Filter_4_full.ipynb
13,path,../data/full,parameter,Filter_4_full.ipynb,Filter_4_full.ipynb
14,filter,37.406,record,Filter_4_full.ipynb,Filter_4_full.ipynb
15,filter_total,55.6387,record,Filter_4_full.ipynb,Filter_4_full.ipynb
16,cores,1,parameter,Read_1_full.ipynb,Read_1_full.ipynb
17,path,../data/full,parameter,Read_1_full.ipynb,Read_1_full.ipynb
18,read,61.2291,record,Read_1_full.ipynb,Read_1_full.ipynb
19,read_total,18.2421,record,Read_1_full.ipynb,Read_1_full.ipynb
20,cores,2,parameter,Read_2_full.ipynb,Read_2_full.ipynb
21,path,../data/full,parameter,Read_2_full.ipynb,Read_2_full.ipynb
22,read,34.8258,record,Read_2_full.ipynb,Read_2_full.ipynb
23,read_total,18.2489,record,Read_2_full.ipynb,Read_2_full.ipynb
24,cores,3,parameter,Read_3_full.ipynb,Read_3_full.ipynb
25,path,../data/full,parameter,Read_3_full.ipynb,Read_3_full.ipynb
26,read,35.9541,record,Read_3_full.ipynb,Read_3_full.ipynb
27,read_total,18.3267,record,Read_3_full.ipynb,Read_3_full.ipynb
28,cores,4,parameter,Read_4_full.ipynb,Read_4_full.ipynb
29,path,../data/full,parameter,Read_4_full.ipynb,Read_4_full.ipynb
30,read,35.8963,record,Read_4_full.ipynb,Read_4_full.ipynb
31,read_total,18.2444,record,Read_4_full.ipynb,Read_4_full.ipynb

In [6]:
df = nbs.dataframe.pivot(index='key', columns='name', values='value')
df["cores"] = pd.to_numeric(df["cores"])
df["filter"] = pd.to_numeric(df["filter"])
df

name,cores,filter,filter_total,path,read,read_total
key,,,,,,
Filter_1_full.ipynb,1,62.542948,80.7885,../data/full,None,None
Filter_2_full.ipynb,2,35.805331,54.0278,../data/full,None,None
Filter_3_full.ipynb,3,36.629864,54.9289,../data/full,None,None
Filter_4_full.ipynb,4,37.405966,55.6387,../data/full,None,None
Read_1_full.ipynb,1,NaN,None,../data/full,61.2291,18.2421
Read_2_full.ipynb,2,NaN,None,../data/full,34.8258,18.2489
Read_3_full.ipynb,3,NaN,None,../data/full,35.9541,18.3267
Read_4_full.ipynb,4,NaN,None,../data/full,35.8963,18.2444

In [7]:
ds = df.filter(like='Filter', axis=0)
ds.to_csv("../results/Filter.csv")